**1. Write a python program which searches all the product under a particular product from www.amazon.in. The 
product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for 
guitars.**

**Answer:-**

In [1]:
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException
import requests

In [18]:
driver=webdriver.Chrome()

In [19]:
driver.get("http://www.amazon.in/")

In [20]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
input_data=input("Enter the product you want")
search.send_keys(input_data)

Enter the product you wantguitar

In [21]:
#Clecking in the search button
hit_search=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
hit_search.click()

**2. In the above question, now scrape the following details of each product listed in first 3 pages of your search 
results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then 
scrape all the products available under that product name. Details to be scraped are: "Brand 
Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and 
“Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.**

**Answer:-**

In [22]:
product_url=[]
start=0
end=3

for page in range(start,end):
    
    product_link_tag=driver.find_elements(By.XPATH,'//h2[@class="a-size-mini a-spacing-none a-color-base s-line-clamp-4"]/a')
    
    for i in product_link_tag:
        
        product_url.append(i.get_attribute('href'))
        
    next_button=driver.find_elements(By.XPATH,'/html/body/div[1]/div[1]/div[1]/div[1]/div/span[1]/div[1]/div[67]/div/div/span/a[3]')
    time.sleep(5)

In [23]:
len(product_url)

180

In [24]:
Brand_Name=[]
Name_of_the_Product=[]
Price=[]
Return_Exchange=[]
Expected_Delivery=[]
Availability=[]

In [25]:
for i in product_url:
    driver.get(i)
    time.sleep(5)
    try:
        Brand_Name_tag=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[5]/div[3]/div[4]/div[46]/div/table/tbody/tr[1]/td[2]/span')
        Brand_Name_text=Brand_Name_tag.text
        Brand_Name.append(Brand_Name_text)
        
        Name_of_the_Product_tag=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[5]/div[3]/div[4]/div[1]/div/h1/span')
        Name_of_the_Product_text=Name_of_the_Product_tag.text
        Name_of_the_Product.append(Name_of_the_Product_text)
        
        Price_tag=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[5]/div[3]/div[4]/div[13]/div/div/div[4]/div[1]/span[3]/span[2]/span[2]')
        Price_text=Price_tag.text
        Price.append(Price_text)
        
        Return_Exchange_tag=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[5]/div[3]/div[4]/div[24]/div[2]/div/div/div/div[2]/div/ol/li[3]/div/span/div[2]/span')
        Return_Exchange_text=Return_Exchange_tag.text
        Return_Exchange.append(Return_Exchange_text)
        
        Expected_Delivery_tag=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[5]/div[3]/div[1]/div[3]/div/div[1]/div/div/div/form/div/div/div/div/div[4]/div/div[3]/div[9]/div[1]/div/div/div/span/span')
        Expected_Delivery_text=Expected_Delivery_tag.text
        Expected_Delivery.append(Expected_Delivery_text)
        
        Availability_tag=driver.find_element(By.XPATH,'/html/body/div[2]/div/div[5]/div[3]/div[1]/div[3]/div/div[1]/div/div/div/form/div/div/div/div/div[4]/div/div[5]/div/div[1]/span')
        Availability_text=Availability_tag.text
        Availability.append(Availability_text)
    
    except NoSuchElementException:
        Brand_Name.append("-")
        Name_of_the_Product.append("-")
        Price.append("-")
        Return_Exchange.append("-")
        Expected_Delivery.append("-")
        Availability.append("-")

In [26]:
print(len(Brand_Name),len(Name_of_the_Product),len(Price),len(Return_Exchange),len(Expected_Delivery),len(Availability))

193 193 193 181 180 180

In [30]:
Product=pd.DataFrame({"Brand Name":Brand_Name[:180],"Name of the Product":Name_of_the_Product[:180],"Price":Price[:180],"Return/Exchange":Return_Exchange[:180],"Expected Delivery":Expected_Delivery[:180],"Availability":Availability[:180],"Product URL":product_url[:180]},index=range(1,181))
Product

,Brand Name,Name of the Product,Price,Return/Exchange,Expected Delivery,Availability,Product URL
1,Kadence,Kadence A281 Professional Acoustic Rosewood gu...,"6,499",7 days Replacement,"Saturday, 18 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,Kadence,Kadence A281BK Professional Acoustic Rosewood ...,"7,199",7 days Replacement,"Tuesday, 14 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Kadence,"Kadence rosewood Guitar Frontier Series, Elect...","4,275",7 days Replacement,"Saturday, 18 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,Henrix,Henrix 38C 38 Inch Cutaway Acoustic Guitar Wit...,"2,849",7 days Replacement,"Saturday, 18 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
5,JUAREZ,"Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...","1,899",7 days Replacement,"Friday, 17 November",In stock,https://www.amazon.in/Juarez-Acoustic-Cutaway-...
...,...,...,...,...,...,...,...
176,JUAREZ,JUAREZ JRZ38C 38 Inches Lindenwood Right Hande...,"2,634",7 days Replacement,-,-,https://www.amazon.in/Yamaha-FSX80C-Acoustic-C...
177,Yamaha,"Yamaha FS100C Acoustic Guitar, Black","9,599",-,"Saturday, 18 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
178,-,-,-,7 days Replacement,-,-,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
179,Kadence,Kadence Slowhand Premium Jumbo Semi Acoustic G...,"7,999",-,-,-,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
180,Intern,Intern Int-38c Sunburst Linden Wood Acoustic G...,"2,260",-,"Tuesday, 14 November",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...

In [31]:
Product.to_csv("Final_sheet.csv",index=False)

**3. Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.**

**Answer:-**

In [2]:
driver=webdriver.Chrome()
driver.get("https://images.google.com/")

In [4]:
enter=input("Enter the product you want to search")
search=driver.find_element(By.XPATH,'//textarea[@class="gLFyf"]')
search.send_keys(enter)

Enter the product you want to searchfruits

In [5]:
button=driver.find_element(By.XPATH,'//button[@class="Tg7LZd"]')
button.click()

In [8]:
for scroll in range(20):
    driver.execute_script("window.scrollBy(0,700)")
    
image=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]') 

img_url=[]

for i in image:
    source=i.get_attribute("src")
    if source is not None:
        if (source[0:4]=='http'):
            img_url.append(source)
            
for l in range(len(img_url)):
    if l>10:
        break
    print("Downloading {} of {} images".format(l,10))
    response=requests.get(img_url[l])
    file=open(r"D:\Scrape_image"+str(l)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

**4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com
and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand 
Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, 
“Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the 
details is missing then replace it by “- “. Save your results in a dataframe and CSV.**

**Answer:-**

In [2]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import re

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get("https://www.flipkart.com/")

In [5]:
delay=10

try:
    pop_up_close=WebDriverWait(driver,delay).until(EC.presence_of_element_located((By.XPATH,"/html/body/div[3]/div/span")))
    pop_up_close.click()
    search_bar=driver.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/header/div[1]/div[2]/form/div/div/input")
    search_bar.send_keys("Oneplus Nord")
    search_button=driver.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/header/div[1]/div[2]/form/div/button")
    search_button.click()
except NoSuchElementException:
    
    search_bar=driver.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/header/div[1]/div[2]/form/div/div/input")
    search_bar.send_keys("Oneplus Nord")
    search_button=driver.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/header/div[1]/div[2]/form/div/button")
    search_button.click()

In [15]:
Brand_Name=[]

In [17]:
try:
    pattern = r"^\w+"
    Brand_Name_tags = driver.find_elements(By.XPATH, '//div[@class="_4rR01T"]')
    
    for Brand_Name_tag in Brand_Name_tags:
        Brand_Name_text = Brand_Name_tag.text
        match = re.search(pattern, Brand_Name_text)
        brand = match.group() if match else "--"
        Brand_Name.append(brand)
    
except NoSuchElementException:
    Brand_Name.append("--")

In [19]:
Smartphone_name=[]

In [20]:
try:
    
    Smartphone_name_tags=driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
    
    for Smartphone_name_tag in Smartphone_name_tags:
        Smartphone_name_text=Smartphone_name_tag.text
        Smartphone_name.append(Smartphone_name_text)
    
except NoSuchElementException:
    Smartphone_name.append("--")

In [22]:
product_link_url=[]

In [23]:

product_link_tag=driver.find_elements(By.XPATH,'//div[@class="_2kHMtA"]/a')
for i in product_link_tag:
    product_link_text=i.get_attribute('href')
    product_link_url.append(product_link_text)

In [24]:
len(product_link_url)

24

In [25]:

Colour=[]
RAM_and_ROM=[]
Primary_and_Secondary_Camera=[]
Display_Size=[]
Battery_Capacity=[]
Price=[]

In [26]:
for i in product_link_url:
    driver.get(i)
    #read_more=driver.find_element(By.XPATH,"/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/button")
    #read_more.click()
    time.sleep(5)
    try:
        
        
        
        
        Colour_tag=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[4]/div/div[2]/div/div[1]/table/tbody/tr[4]/td[2]/ul/li')
        Colour_text=Colour_tag.text
        Colour.append(Colour_text)
        
        RAM_and_ROM_tag=driver.find_element(By.XPATH,'//div[@class="_2418kt"]/ul/li[1]')
        RAM_and_ROM_text=RAM_and_ROM_tag.text
        RAM_and_ROM.append(RAM_and_ROM_text)
        
        Primary_and_Secondary_Camera_tag=driver.find_element(By.XPATH,'//div[@class="_2418kt"]/ul/li[3]')
        Primary_and_Secondary_Camera_text=Primary_and_Secondary_Camera_tag.text
        Primary_and_Secondary_Camera.append(Primary_and_Secondary_Camera_text)
        
        Display_Size_tag=driver.find_element(By.XPATH,'//div[@class="_2418kt"]/ul/li[2]')
        Display_Size_text=Display_Size_tag.text
        Display_Size.append(Display_Size_text)
        
        Battery_Capacity_tag=driver.find_element(By.XPATH,'//div[@class="_2418kt"]/ul/li[4]')
        Battery_Capacity_text=Battery_Capacity_tag.text
        Battery_Capacity.append(Battery_Capacity_text)
        
        
        Price_tag=driver.find_element(By.XPATH,'//div[@class="_30jeq3 _16Jk6d"]')
        Price_text=Price_tag.text
        Price.append(Price_text)
        
        
    
    except NoSuchElementException:
        
        Colour.append("--")
        RAM_and_ROM.append("--")
        Primary_and_Secondary_Camera.append("--")
        Display_Size.append("--")
        Battery_Capacity.append("--")
        Price.append("--")

In [28]:
print(len(Brand_Name),len(Smartphone_name),len(Colour),len(RAM_and_ROM),len(Primary_and_Secondary_Camera),len(Display_Size),len(Battery_Capacity),len(Price))

24 24 24 24 24 24 24 24

In [29]:
Product_Details=pd.DataFrame({"Brand Name":Brand_Name,"Smartphone Name":Smartphone_name,"Colour":Colour,"RAM AND ROM":RAM_and_ROM,"Primary And Secondary Camera":Primary_and_Secondary_Camera,"Display Size":Display_Size,"Battery Capacity":Battery_Capacity,"Price":Price,"Product URL":product_link_url})
Product_Details

,Brand Name,Smartphone Name,Colour,RAM AND ROM,Primary And Secondary Camera,Display Size,Battery Capacity,Price,Product URL
0,OnePlus,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)",Blue Tide,6 GB RAM | 128 GB ROM,64MP Rear Camera | 16MP Front Camera,16.74 cm (6.59 inch) Display,5000 mAh Battery,"₹17,179",https://www.flipkart.com/oneplus-nord-ce-2-lit...
1,OnePlus,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB)",Pastel Lime,8 GB RAM | 128 GB ROM,108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹19,697",https://www.flipkart.com/oneplus-nord-ce-3-lit...
2,OnePlus,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB)",Pastel Lime,8 GB RAM | 256 GB ROM,108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹21,740",https://www.flipkart.com/oneplus-nord-ce-3-lit...
3,OnePlus,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...",Chromatic Gray,8 GB RAM | 256 GB ROM,108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹21,686",https://www.flipkart.com/oneplus-nord-ce-3-lit...
4,OnePlus,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",Chromatic Gray,8 GB RAM | 128 GB ROM,108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹19,965",https://www.flipkart.com/oneplus-nord-ce-3-lit...
5,OnePlus,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)",--,--,--,--,--,--,https://www.flipkart.com/oneplus-nord-ce-2-lit...
6,OnePlus,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 128 GB)",--,--,--,--,--,--,https://www.flipkart.com/oneplus-nord-ce-3-lit...
7,OnePlus,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...",Chromatic Gray,8 GB RAM | 256 GB ROM,108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹21,985",https://www.flipkart.com/oneplus-nord-ce-3-lit...
8,OnePlus,"OnePlus Nord CE 3 Lite 5G (Pastel lime, 256 GB)",Pastel lime,8 GB RAM | 256 GB ROM,108MP Rear Camera,17.07 cm (6.72 inch) Display,5000 mAh Battery,"₹21,997",https://www.flipkart.com/oneplus-nord-ce-3-lit...
9,OnePlus,"OnePlus Nord CE3 5G (Grey Shimmer, 256 GB)",Grey Shimmer,12 GB RAM | 256 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,5000 mAh Battery,"₹28,999",https://www.flipkart.com/oneplus-nord-ce3-5g-g...
10,OnePlus,"OnePlus Nord CE3 5G (Aqua Surge, 256 GB)",Aqua Surge,12 GB RAM | 256 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,5000 mAh Battery,"₹28,999",https://www.flipkart.com/oneplus-nord-ce3-5g-a...
11,OnePlus,"OnePlus Nord CE3 5G (Grey Shimmer, 128 GB)",Grey Shimmer,8 GB RAM | 128 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,5000 mAh Battery,"₹25,662",https://www.flipkart.com/oneplus-nord-ce3-5g-g...
12,OnePlus,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 256...",--,--,--,--,--,--,https://www.flipkart.com/oneplus-nord-ce-3-lit...
13,OnePlus,"OnePlus Nord CE3 5G (Aqua Surge, 128 GB)",Aqua Surge,8 GB RAM | 128 GB ROM,50MP Rear Camera,17.02 cm (6.7 inch) Display,5000 mAh Battery,"₹25,548",https://www.flipkart.com/oneplus-nord-ce3-5g-a...
14,OnePlus,"OnePlus Nord CE 3 Lite 5G (Pastel Lime, 256 GB)",--,--,--,--,--,--,https://www.flipkart.com/oneplus-nord-ce-3-lit...
15,OnePlus,"OnePlus Nord 3 5G (Tempest Gray, 128 GB)",Tempest Gray,8 GB RAM | 128 GB ROM,50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹31,790",https://www.flipkart.com/oneplus-nord-3-5g-tem...
16,OnePlus,"OnePlus Nord 3 5G (Misty Green, 128 GB)",Misty Green,8 GB RAM | 128 GB ROM,50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹31,777",https://www.flipkart.com/oneplus-nord-3-5g-mis...
17,OnePlus,"OnePlus Nord 3 5G (Tempest Gray, 256 GB)",Tempest Gray,16 GB RAM | 256 GB ROM,50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹36,450",https://www.flipkart.com/oneplus-nord-3-5g-tem...
18,OnePlus,"OnePlus Nord 3 5G (Misty Green, 256 GB)",Misty Green,16 GB RAM | 256 GB ROM,50MP Rear Camera,17.12 cm (6.74 inch) Display,5000 mAh Battery,"₹35,899",https://www.flipkart.com/oneplus-nord-3-5g-mis...
19,OnePlus,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",--,--,--,--,--,--,https://www.flipkart.com/oneplus-nord-ce-3-lit...
20,OnePlus,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)",--,--,--,--,--,--,https://www.flipkart.com/oneplus-nord-2t-5g-gr...
21,OnePlus,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)",--,--,--,--,--,--,https://www.flipkart.com/oneplus-nord-2t-5g-ja...
22,OnePlus,"OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 128...",--,--,--,--,--,--,https://www.flipkart.com/oneplus-nord-ce-3-lit...
23,OnePlus,"OnePlus Nord 2T 5G (Gray Shadow, 256 GB)",--,--,--,--,--,--,https://www.flipkart.com/oneplus-nord-2t-5g-gr...

In [30]:
#Creating_csv
Product_Details.to_csv("Product.csv",index=False)

In [ ]:
driver.close()

**5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.**

**Answer:-**

In [35]:
driver=webdriver.Chrome()

In [36]:
driver.get("https://www.google.com/maps")
time.sleep(3)

location_name=input("Enter the location name")
search_bar=driver.find_element(By.XPATH,"/html/body/div[3]/div[8]/div[3]/div[1]/div[1]/div/div[2]/form/input")
search_bar.clear()                             #clearing the searchbar
search_bar.send_keys(location_name)

search_button=driver.find_element(By.XPATH,"/html/body/div[3]/div[8]/div[3]/div[1]/div[1]/div/div[2]/div[1]/button")
search_button.click()

try:
    url=driver.current_url         #fetching current url open in Chrome 
    print("Your location url is :",url)
    latitude_longitude=re.findall(r"@(\d+\.\d+),(\d+\.\d+)",url)


    if latitude_longitude:
        for latitude,longitude in latitude_longitude:
            print("latitude = {} and longitude = {}".format(latitude,longitude))
    
    else:
        print("Unable to find Latitude and Longitude")
        
except NoSuchElementException:
    print("Error")
    
driver.close()

Enter the location nameRamjibanpur
Your location url is : https://www.google.com/maps/@26.5715712,88.2802688,12z?entry=ttu
latitude = 26.5715712 and longitude = 88.2802688

**6. Write a program to scrap all the available details of best gaming laptops from digit.in.**

**Answer:-**

In [105]:
driver=webdriver.Chrome()

In [106]:
driver.get("https://www.digit.in/")

#clicking on top 10 tab
top_10=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]/a")
top_10.click()

time.sleep(3)

#clicking on top 10 best laptop in india
top_10_best_lap=driver.find_element(By.XPATH,'/html/body/div[1]/div[3]/div/div[2]/div[1]/div[3]/div[6]/p/a')
top_10_best_lap.click()

time.sleep(3)

In [107]:
p_name=[]
description=[]
os=[]
processor=[]
sd=[]
display=[]
product_url=[]

In [108]:
# Fetching product name
try:
    names = driver.find_elements(By.XPATH, '//h3[@class="font130 mt0 mb10 mobilesblockdisplay "]/a')
    
    for name in names:
        name_text = name.text
        p_name.append(name_text)
except NoSuchElementException:
    p_name.append("--")

In [109]:
len(p_name)

6

In [110]:
url=driver.find_elements(By.XPATH,'//h3[@class="font130 mt0 mb10 mobilesblockdisplay "]/a')
for i in url:
    product_url.append(i.get_attribute('href'))

In [111]:
len(product_url)

6

In [112]:
product_url

['https://www.digit.in/laptops/apple-macbook-air-2022-m2-mly03hn-a-price-330027.html',
 'https://www.digit.in/laptops/samsung-galaxy-book3-pro-360-np960qfg-ka1in-13th-gen-core-i7-1360p-2023-price-343761.html',
 'https://www.digit.in/laptops/lenovo-yoga-9i13th-gen-core-i7-i7-1360p-price-346092.html',
 'https://www.digit.in/laptops/apple-macbook-pro-m2-2023-mphk3hn-a-price-344778.html',
 'https://www.digit.in/laptops/dell-xps-13-plus-d560075win9s-12th-gen-core-i7-1260p-2022-price-330657.html',
 'https://www.digit.in/laptops/acer-swift-x-sfx16-51g-11th-gen-core-i7-11390h-price-346119.html']

In [116]:
for i in product_url:
    driver.get(i)
    time.sleep(5)
    

    # Fetching OS name
    try:
        description_tags = driver.find_elements(By.XPATH, '//div[@class="specs_details "]/ul/li')
    
        for p in description_tags:
            description_text = p.text
            description.append(description_text)
            
            
    except NoSuchElementException:
        description.append("--")

In [117]:
print(len(p_name), len(description))

6 24

In [120]:
for i in range(0, len(description), 4):
    product_info = description[i:i+4] 
    
    os_info = product_info[0].split('\n')[1]  
    processor_info = product_info[1].split('\n')[1] 
    sd_info = product_info[2].split('\n')[1]  
    display_info = product_info[3].split('\n')[1]  
    
    
    os.append(os_info)
    processor.append(processor_info)
    sd.append(sd_info)
    display.append(display_info)

In [121]:
df=pd.DataFrame({"Product Name":p_name,"Operating System":os,"Display Size":display,"Storage Size":sd,"Processor":processor})
df

,Product Name,Operating System,Display Size,Storage Size,Processor
0,Apple MacBook Air 2022 M2 MLY03HN/A,IOS,Windows 11,Mac,Windows 11 Home
1,Samsung Galaxy Book3 Pro 360,Windows 11 Home,512 GB,Apple M2,IOS
2,Lenovo Yoga 9i13th Gen Core i7-1360P,13.6,512 GB,13th Gen Intel Core I7-1360P,Windows 11 Home
3,Apple MacBook Pro M2 (2023-MPHK3HN/A),14,14.2,1 TB,Mac
4,Dell XPS 13 Plus D560075WIN9S 12th Gen Core i7...,Windows 11,13.4,1 TB,12th Gen Intel EVO Core I7-1260P
5,Acer Swift X SFX16-51G 11th Gen Core i7-11390H,Windows 11 Home,16,1 TB,11th Gen Intel Core I7-11390H

**7. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”,“Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.**

**Answer:-**

In [94]:
driver=webdriver.Chrome()
driver.get("https://www.forbes.com/billionaires/")
time.sleep(5)

Rank=[]
Name=[]
Net_worth=[]
Age=[]
Citizenship=[]
Source=[]
Industry=[]

try:
    rank_tag=driver.find_elements(By.XPATH,'//div[@class="TableRow_cell__db-hv Table_cell__houv9"][1]')
    for i in rank_tag:
        rank_text=i.text
        Rank.append(rank_text)
    
    Name_tag=driver.find_elements(By.XPATH,'//div[@class="TableRow_cell__db-hv Table_cell__houv9"][2]')
    for p in Name_tag:
        name_text=p.text
        Name.append(name_text)
        
    Net_tag=driver.find_elements(By.XPATH,'//div[@class="TableRow_cell__db-hv Table_cell__houv9"][3]')
    for n in Net_tag:
        net_text=n.text
        Net_worth.append(net_text)
        
    Age_tag=driver.find_elements(By.XPATH,'//div[@class="TableRow_cell__db-hv Table_cell__houv9"][4]')
    for a in Age_tag:
        age_text=a.text
        Age.append(age_text)
     
    Citizenship_tag=driver.find_elements(By.XPATH,'//div[@class="TableRow_cell__db-hv Table_cell__houv9"][5]')
    for c in Citizenship_tag:
        city_text=c.text
        Citizenship.append(city_text)
    
    Source_tag=driver.find_elements(By.XPATH,'//div[@class="TableRow_cell__db-hv Table_cell__houv9"][6]')
    for s in Source_tag:
        Source_text=s.text
        Source.append(Source_text)
        
    Industry_tag=driver.find_elements(By.XPATH,'//div[@class="TableRow_cell__db-hv Table_cell__houv9"][7]')
    for I in Industry_tag:
        Industry_text=I.text
        Industry.append(Industry_text)
    
except NoSuchElementException:
    Rank.append("--")
    Name.append("--")
    Net_worth.append("--")
    Age.append("--")
    Citizenship.append("--")
    Source.append("--")
    Industry.append("--")
    

billionaires=pd.DataFrame({"Rank":Rank,"Name":Name,"Net_worth":Net_worth,"Age":Age,"Citizenship":Citizenship,"Source":Source,"Industry":Industry})   
billionaires    
    
driver.close()

,Rank,Name,Net_worth,Age,Citizenship,Source,Industry
0,1,Bernard Arnault & family,$211 B,74,France,LVMH,Fashion & Retail
1,2,Elon Musk,$180 B,51,United States,"Tesla, SpaceX",
2,3,Jeff Bezos,$114 B,59,United States,Amazon,
3,4,Larry Ellison,$107 B,78,United States,Oracle,
4,5,Warren Buffett,$106 B,92,United States,Berkshire Hathaway,
...,...,...,...,...,...,...,...
195,195,Jin Baofang,$9.6 B,70,China,Solar panels,
196,195,Luo Liguo & family,$9.6 B,67,China,Chemicals,
197,195,Marijke Mars,$9.6 B,58,United States,"Candy, pet food",
198,195,Pamela Mars,$9.6 B,62,United States,"Candy, pet food",
199,195,Valerie Mars,$9.6 B,64,United States,"Candy, pet food",

**8. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.**

**Answer:-**

In [135]:
url="https://www.youtube.com/watch?v=jcgM1W6CtqA"

driver=webdriver.Chrome()
driver.get(url)

In [136]:
for page in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [137]:
Comments=[]
Comment_upvote=[]
time=[]

In [138]:
comment_tag=driver.find_elements(By.XPATH,'//yt-formatted-string[@id="content-text"]')
for i in comment_tag:
    comment_text=i.text
    Comments.append(comment_text)
    
upvote_tag=driver.find_elements(By.XPATH,'//span[@id="vote-count-middle"]')
for u in upvote_tag:
    upvote_text=u.text
    Comment_upvote.append(upvote_text)
    
time_tag=driver.find_elements(By.XPATH,'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]/a')
for t in time_tag:
    time_text=t.text
    time.append(time_text)

In [139]:
Comments_df=pd.DataFrame({"Comments":Comments[:500],"Comment upvote":Comment_upvote[:500],"Time of postage":time[:500]},index=range(1,501))
Comments_df

,Comments,Comment upvote,Time of postage
1,Doston Aapko Ye Smart Ring Kaisi Lagi?,741,2 months ago
2,9k mein ek gold ring aa jayega Big L for boat,6.3K,2 months ago
3,I'm glad that they are out with innovative pro...,43,2 months ago (edited)
4,Feels good to see indian companies growing \nH...,334,2 months ago
5,The product we never wanted,387,2 months ago
...,...,...,...
496,10g ki gold ring aa jaegi itni price mein \nky...,,2 months ago
497,Chiz badhiya hai rapchik chiz hai\nPar isme kh...,,2 months ago
498,Agar hath se washroom me kuch galat kam krege ...,,2 months ago
499,Zaroorat nahi thi uski. Same to same smart wat...,,3 days ago
500,App kounsa mobile use karte hou?,,2 months ago

**9. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description**

**Answer:-**

In [127]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [84]:
driver=webdriver.Chrome()
driver.get("https://www.hostelworld.com/")

In [89]:
search_bar=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[1]/div/div[2]/input')
search_bar.send_keys("London")

In [91]:
sel_option=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[2]/div/ul/li[2]/button')
sel_option.click()

In [92]:
search_button=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[5]/button[1]')
search_button.click()

In [93]:
Name=[]
distance=[]
ratings=[]
private_price=[]
dorms_price=[]
facilities_and_property_description=[]

In [94]:

name_tag=driver.find_elements(By.XPATH,'//div[@class="property-name"]')
for n in name_tag:
    name_text=n.text
    Name.append(name_text)
distance_tag=driver.find_elements(By.XPATH,'//span[@class="distance-description"]')   
for d in distance_tag:
    distance_text=d.text
    distance.append(distance_text)
ratings_tag=driver.find_elements(By.XPATH,'//span[@class="number"]')
for r in ratings_tag:
    ratings_text=r.text
    ratings.append(ratings_text)
    
price_tag=driver.find_elements(By.XPATH,'//div[@class="accommodation-price"]/strong')
for n in price_tag:
    price_text=n.text
    dorms_price.append(price_text)

In [95]:
print(len(Name),len(distance),len(ratings),len(dorms_price))

32 30 31 34

In [96]:
urls=[]

In [97]:
url=driver.find_elements(By.XPATH,'//div[@class="property-card"]/a/a')
for i in url:
    urls.append(i.get_attribute('href'))

In [98]:
len(urls)

32

In [99]:
for M in urls:
    driver.get(M)
    try:
        des=driver.find_elements(By.XPATH,'//div[@class="content collapse-content"]')
        for tag in des:
            des_tag=tag.text
            facilities_and_property_description.append(des_tag)
    except NoSuchElementException:
        facilities_and_property_description.append("--")

In [104]:
Hostel=pd.DataFrame({"Hostel Name":Name[2:],"Distance":distance,"Ratings":ratings[1:],"Property Description":facilities_and_property_description[:60:2],"Drom Price":dorms_price[3:33]})
Hostel

,Hostel Name,Distance,Ratings,Property Description,Drom Price
0,Wombat's City Hostel London,- 3.6km from city centre,8.8,St Christopher's Inn at The Village in London ...,"₹5,042"
1,St Christopher's Village,- 1.8km from city centre,9.0,I had a very nice stay. Staff were very friend...,"₹3,607"
2,Urbany Hostel London,- 5.4km from city centre,8.1,"Whether you're a backpacker, flash-packer or a...","₹20,101"
3,Palmers Lodge - Swiss Cottage,- 6.5km from city centre,9.5,Best hostel I’ve ever stayed in. The decor is ...,"₹4,004"
4,Generator London,- 3km from city centre,8.8,I loved staying at Wombat Hostel! It’s my firs...,"₹5,003"
5,Safestay London Elephant & Castle,- 1.7km from city centre,7.5,nice hostel with lots of spaces and activities...,"₹3,176"
6,NX London Hostel,- 6.1km from city centre,7.1,"Thank you so much for everything ,great friend...","₹7,621"
7,Astor Museum Inn,- 2.2km from city centre,8.4,"The location of this hostel was fantastic, rig...","₹4,143"
8,No.8 Willesden Hostel London,- 10km from city centre,8.4,Perfect place to stay in London. The hostel is...,"₹1,840"
9,Safestay London Kensington Holland Park,- 5.8km from city centre,7.1,"Whether you're a backpacker, flash-packer or a...","₹2,634"
10,Queen Elizabeth Chelsea,- 5.7km from city centre,6.9,Best hostel I’ve ever stayed in. The decor is ...,"₹2,687"
11,Phoenix Hostel,- 4.2km from city centre,7.4,A good hostel except our dorm was TINY! In our...,"₹3,568"
12,Smart Hyde Park Inn Hostel,- 5km from city centre,7.0,The locks on the room toilets did not work and...,"₹4,916"
13,Hostelle - women only hostel London,- 5.1km from city centre,7.6,Welcome to NX London Hostel!\n\nPLEASE READ IN...,"₹5,745"
14,St Christopher's Hammersmith,- 7.5km from city centre,8.7,he tenido el placer de hospedarme en el Hostal...,"₹3,328"
15,Astor Victoria,- 1.8km from city centre,7.6,This Hostel has been nothing short of amazing ...,"₹3,029"
16,Saint James Backpackers,- 5.5km from city centre,7.1,Probably the best hostel in London. If you are...,"₹4,167"
17,Astor Kensington,- 4.9km from city centre,7.7,"It was a good stay for the price. Obviously, y...","₹3,934"
18,St Christopher's Camden,- 4.3km from city centre,8.6,Clean and cheerful. Great location and very go...,"₹4,894"
19,St Christopher's Greenwich,- 7.6km from city centre,7.5,Staff was very friendly. Hostel within walking...,"₹3,120"
20,Park Villa,- 6.3km from city centre,7.3,My stay here was epic! The staff here were sup...,"₹5,662"
21,Bell House Hostel,- 4.2km from city centre,8.9,"The Phoenix Bar & Hostel, housed in a homely E...","₹3,635"
22,"PubLove @ The Crown, Battersea",- 4.7km from city centre,7.1,"Stayed 2 weeks, in 2 mixed rooms with 4-beds &...","₹5,501"
23,Selina Camden,- 5.5km from city centre,7.0,Hostelle is the first and only all-women hoste...,"₹30,164"
24,Onefam Waterloo,- 0.7km from city centre,8.7,Really lovely hostel to stay in. Social place ...,"₹11,877"
25,"PubLove @ The White Ferry, Victoria",- 2.4km from city centre,6.7,I really enjoyed this Hostel. The rooms felt v...,"₹3,236"
26,Kensal Green Backpackers,- 8.2km from city centre,5.1,With Victoria Station and Buckingham Palace a ...,"₹4,874"
27,"PubLove @ The Exmouth Arms, Euston",- 3.4km from city centre,6.7,Very clean hostel. Nice and quiet at night as ...,"₹2,437"
28,"PubLove @ The Green Man, Paddington",- 4.3km from city centre,6.3,Absolutely great hostel. Was very comfortable ...,"₹5,396"
29,Tony's House Hotel,- 4.3km from city centre,6.1,"Located a short walk from Notting Hill, Hyde P...","₹4,700"